name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: yarn serve
          env: TEST_ENV=${{ secrets.TEST_ENV }}
          wait-on: 'http://localhost:5000'